[build-system]

# See https://github.com/scipy/oldest-supported-numpy deprecation notice
requires = [
    "setuptools",
    "wheel",
    "numpy>=1.24",
]

[tool.ruff]
preview = true
# FIXME
line-length = 100

[tool.ruff.lint]
extend-select = [
    "B",   # flake8-bugbear
    "C",   # flake8-comprehensions
    "E",   # pycodestyle
    "F",   # pyflakes
    "G",   # flake8-logging-format
    "I",   # flake8-isort
    "N",   # pep8-naming
    "NPY", # numpy
    "PGH", # pygrep-hooks
    "Q",   # flake8-quotes
    "RUF", # ruff
    "SIM", # flake8-simplify
    "TC",  # flake8-type-checking
    "UP",  # pyupgrade
    "W",   # pycodestyle
]
extend-ignore = [
    "C90",
    "multiple-spaces-before-operator",
    "missing-whitespace-around-arithmetic-operator",
    "module-import-not-at-top-of-file",
    "printf-string-formatting",
    "f-string",
    "numpy-legacy-random",
    "collapsible-if",
    "blanket-noqa",
    "raise-without-from-inside-except",
    "mutable-class-default",
    "if-else-block-instead-of-if-exp",
    "non-empty-init-module",
    "float-equality-comparison",
    "blind-except",
]

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "double"
multiline-quotes = "double"

[tool.ruff.lint.isort]
combine-as-imports = true
known-local-folder = [
    "pycuda",
]
known-first-party = [
    "pytools",
]
lines-after-imports = 2
required-imports = ["from __future__ import annotations"]

[tool.ruff.lint.pep8-naming]
extend-ignore-names = ["update_for_*"]

[tool.ruff.lint.per-file-ignores]
"doc/conf.py" = ["exec-builtin"]
"test/test_*.py" = [
    "non-lowercase-variable-in-function",
    "exec-builtin",
]
"setup.py" = [
    "non-lowercase-variable-in-function",
    "open-file-with-context-handler",
    "exec-builtin",
]
"pycuda/sparse/coordinate.py" = [
    "line-too-long", # line length
]
"pycuda/driver.py" = [
    "undefined-local-with-import-star-usage",
    "non-lowercase-variable-in-function",
]
"pycuda/curandom.py" = [
    "line-too-long", # line length
]
"examples/from-wiki/*.py" = [
    "F", "E", "N", "B", "shebang-not-executable", "PLW",
]
"examples/demo_cdpSimplePrint.py" = [
    "line-too-long", # line length
    "mixed-case-variable-in-global-scope", # mixed case locals
]
"aksetup_helper.py" = [
    # effectively unmaintained, will go away
    "UP", "C", "line-too-long", "B", "SIM", "RUF", "exec-builtin", "try-except-pass", "TRY"
]
"test/undistributed/*.py" = ["B"]
